












NNODES=4
NGPU=32

EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 SHOULD_PROFILE_MEMORY=1 BATCH_SIZE=1 NUM_LAYERS=32 NUM_TOKENS=262144 ELONGATE_FACTOR=4 MAX_SAMPLE_ID=2 bash test_e2e_combined.onesrun.sh


EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 SHOULD_PROFILE_MEMORY=1 BATCH_SIZE=1 NUM_LAYERS=32 NUM_TOKENS=262144 ELONGATE_FACTOR=4 MAX_SAMPLE_ID=2 bash test_e2e_combined.onesrun.sh


EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 SHOULD_PROFILE_MEMORY=1 BATCH_SIZE=1 NUM_LAYERS=32 NUM_TOKENS=65535 ELONGATE_FACTOR=4 MAX_SAMPLE_ID=2 bash test_e2e_combined.onesrun.sh


EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 SHOULD_PROFILE_MEMORY=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=262144 ELONGATE_FACTOR=4 MAX_SAMPLE_ID=2 bash test_e2e_combined.onesrun.sh


EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 SHOULD_PROFILE_MEMORY=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=65536 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=2 bash test_e2e_combined.onesrun.sh


EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 SHOULD_PROFILE_MEMORY=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=65536 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=2 bash test_e2e_combined.onesrun.sh


SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=65536 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=2 bash test_e2e_combined.onesrun.sh


SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=1 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=65536 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=3 bash test_e2e_combined.onesrun.sh

SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=1 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=16384 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=3 bash test_e2e_combined.onesrun.sh

SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=1 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=16384 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=3 bash test_e2e_combined.onesrun.sh


EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=1 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=65535 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=3 bash test_e2e_combined.onesrun.sh

EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=0 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=1 NUM_LAYERS=4 NUM_TOKENS=65535 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=3 bash test_e2e_combined.onesrun.sh

EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=1 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=2 NUM_LAYERS=4 NUM_TOKENS=65535 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=3 bash test_e2e_combined.onesrun.sh


EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=1 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=2 NUM_LAYERS=4 NUM_TOKENS=131070 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=1 bash test_e2e_combined.onesrun.sh

EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=1 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=1 BATCH_SIZE=2 NUM_LAYERS=4 NUM_TOKENS=16384 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=1 bash test_e2e_combined.onesrun.sh


EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=1 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=0 BATCH_SIZE=2 NUM_LAYERS=4 NUM_TOKENS=16384 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=1 bash test_e2e_combined.onesrun.sh


EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=1 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=0 BATCH_SIZE=2 NUM_LAYERS=4 NUM_TOKENS=65535 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=1 bash test_e2e_combined.onesrun.sh


EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=0 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=0 BATCH_SIZE=2 NUM_LAYERS=4 NUM_TOKENS=65536 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=1 bash test_e2e_combined.onesrun.sh


EXPERIMENT_DEBUG_SET_METADATA_TRANSFER_SIZE_TO_0=1 SHOULD_RESEND_QKV=1 EXPERIMENT_WARMUP_TIMEOUT_SEC=300 EXPERIMENT_WARMUP_TIMES=3 EXPERIMENT_REPEAT_TIMES=1 EXPERIMENT_NVSHMEM_BUFFER_SIZE_GB=6 EXPERIMENT_LOG_MEMORY_USAGE=0 BATCH_SIZE=2 NUM_LAYERS=4 NUM_TOKENS=65536 ELONGATE_FACTOR=1 MAX_SAMPLE_ID=1 bash test_e2e_combined.onesrun.sh



# srun --time=00:10:00 -N 32 -G 256 --ntasks-per-node=1 --jobid=679144 \
#     --output=${LOG_DIR}/%N.%j.out \
#     --error=${LOG_DIR}/%N.%j.out \
#     bash -lc "
#         set -x
#         exec torchrun --nnodes=32 --nproc_per_node=8 --rdzv_backend=c10d --rdzv_endpoint=fs-mbz-gpu-017:29500 --rdzv_id=fs-mbz-gpu-017 --max_restarts=0 test_e2e_combined.py --model-path deepseek-ai/DeepSeek-R1-Distill-Llama-8B --mode d2 --replan-iter 0 --batch-size $BATCH_SIZE --num-nodes 32 --num-gpus-per-node 8 --num-layers $NUM_LAYERS --max-sample-id $MAX_SAMPLE_ID --tp-size 8 --cp-degree 1 --up-sample-factor 4 --num-tokens $NUM_TOKENS --elongate-factor $ELONGATE_FACTOR --filter-threshold 65536 --filter-ratio 0.50 --output-dir ${OUTPUT_DIR} --should-add-debug-cases $MEMORY_PROFILE_ARG
#     "